version: '3.8'
services:
  php:
    image: php:7.4-fpm
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}

  mysql:
    image: mysql:5.7
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: manual_de_vida
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./backend:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - app-network

  frontend:
    image: node:14
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm start"
    ports:
      - "3000:3000"
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
